# Generated by Django 6.0.7 on 2026-07-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-application_date']},
        ),
    ]
